services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: mealplanning-base
    # Use a dummy command so this container doesn't run anything.
    command: ["true"]
    
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_CONFIG_ENHANCED_COOKIE_SECURITY=False
    volumes:
      - ./data_pgadmin:/var/lib/pgadmin      
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - pg-network      

  meal_ingest:
    build:
      context: .
      dockerfile: Dockerfile_meal_ingest
    depends_on:
      - postgres
      - base  # ensure the base image is built first
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - TABLE_NAME=${TABLE_NAME}
      - REPO_URL=${REPO_URL}
      - CLONE_DIR=/app/clone_dir
    networks:
      - pg-network

  data_processor:
    build:
      context: .
      dockerfile: Dockerfile_data_processor      
    depends_on:
      - postgres
      - base  # ensure the base image is built first
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - TABLE_NAME=${TABLE_NAME}
      - SCHEMA_NAME=${SCHEMA_NAME}
      - LAST_MODIFIED_DATE=${LAST_MODIFIED_DATE}
      - NUM_RECIPES=${NUM_RECIPES}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FOOD_LIST_PATH=${FOOD_LIST_PATH}
      - FORCE_UPDATE_PROCESSED=${FORCE_UPDATE_PROCESSED}
    networks:
      - pg-network

  meal_planner:
    build:
      context: .
      dockerfile: Dockerfile_meal_planner
    depends_on:
      - postgres
      - base
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    networks:
      - pg-network     

volumes:
  pgdata:
networks:
  pg-network:
